dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.3.0
    - name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
      alias: rabbitmq
