affinity: {}
configmaps: []
endpoints: []
extraArgs: []
extraHostVolumeMounts: []
hostNetwork: true
image:
  pullPolicy: IfNotPresent
  repository: quay.io/prometheus/node-exporter
  tag: v0.18.1
namespaceOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
prometheus:
  monitor:
    additionalLabels: {}
    enabled: false
    namespace: ""
    scrapeTimeout: 10s
rbac:
  create: true
  pspEnabled: true
resources: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
service:
  annotations:
    prometheus.io/scrape: "true"
  nodePort: null
  port: 9100
  targetPort: 9100
  type: ClusterIP
serviceAccount:
  create: true
  imagePullSecrets: []
  name: null
tolerations:
- effect: NoSchedule
  operator: Exists
