apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudlaunch.fullname" . }}-nginx-conf
  labels:
    app: {{ template "cloudlaunch.name" . }}
    chart: {{ template "cloudlaunch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |-
    upstream cloudlaunch_server {
      server {{ template "cloudlaunchserver.fullname" . }}:8000;
    }
    
    server {
        listen   *:80;
{{- if join " " .Values.ingress.hosts }}
        server_name {{ join " " .Values.ingress.hosts }};
{{- end }}
    
        client_max_body_size 4G;
        gzip on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_min_length 1100;
        gzip_buffers 16 8k;
        gzip_types
            text/plain
            text/css
            text/js
            text/xml
            text/javascript
            application/javascript
            application/x-javascript
            application/json
            application/xml
            application/rss+xml
            image/svg+xml;
    
        location /static/ {
            alias   /usr/share/nginx/html/static/;
        }
    
        location / {
            alias   /usr/share/nginx/html/;
            try_files $uri @proxy /index.html =404;
        }

        location @proxy {
            proxy_pass http://cloudlaunch_server;
        }
    }
