name: Clone charts repository to cloud buckets
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  aws_clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: azure/setup-helm@v1
        with:
          version: '3.6.3'
        id: helm_install
      - run: "mkdir -p aws/charts && cp charts/* aws/charts/ && cd aws/ && helm repo index . --url https://charts.usegalaxy.org"
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'aws'
